Lkt: add more PropertyError constraints
AdaCore/langkit pull request #583
Opened 2021-11-12 14:09 UTC by thvnx

This patch allows to forbid the use of PropertyError as a type,
and enforces that ``raise`` can only calls a ``PropertyError()``.

2021-11-12 16:41 UTC, pmderodat requested changes

2021-11-12 16:41 UTC, pmderodat commented on contrib/lkt/language/parser.py
> +            # and correct call to PropertyError exception.
The comment is not very clear:

> […] check that this call is the operand of a raise expression and this is a call to the PropertyError constructor.

2021-11-12 16:41 UTC, pmderodat commented on contrib/lkt/language/parser.py
> +                        Not(Entity.first_no_paren_parent.is_a(T.RaiseExpr)),
As we don’t have keyword to make it clear what is a condition and what is an expression for the result, we customarily group corresponding conditions/results together. In a conventional language, where we would have:

```
if C1:
   return E1
elif C2:
   return E2
else:
   return E3
```

we do this in the DSL:

```
Cond(
    C1,
    E1,

    C2,
    E2,

    E3,
)
```

Can you adjust the empty lines accordingly?

2021-11-12 16:41 UTC, pmderodat commented on contrib/lkt/language/parser.py
> +                        Not(Entity.called_decl == Entity.property_error_type),
Can you use the `!=` operator to make this condition easier to read?

2021-11-12 16:41 UTC, pmderodat commented on contrib/lkt/language/parser.py
> +                        .concat(S("` is not a type"))
I think we should avoid pretending that `PropertyError` is not a type (it’s a struct in the prelude, so technically it is a type). What about:
> PropertyError can only be referenced in a raise expression

2021-11-12 21:30 UTC, thvnx commented
@pmderodat, thanks for your comments and suggestions. Should be fixed accordingly now.

2021-11-15 17:00 UTC, pmderodat approved these changes

2021-11-17 21:15 UTC, merged